// Copyright 2025 OpenPubkey
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// SPDX-License-Identifier: Apache-2.0

package commands

import (
	"bytes"
	"context"
	"crypto"
	"crypto/ecdsa"
	"crypto/sha256"
	"encoding/base64"
	"encoding/hex"
	"encoding/json"
	"encoding/pem"
	"errors"
	"fmt"
	"io"
	"log"
	"math"
	"net"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"slices"
	"strconv"
	"strings"
	"time"

	"github.com/openpubkey/openpubkey/client"
	"github.com/openpubkey/openpubkey/client/choosers"
	"github.com/openpubkey/openpubkey/jose"
	"github.com/openpubkey/openpubkey/oidc"
	"github.com/openpubkey/openpubkey/pktoken"
	"github.com/openpubkey/openpubkey/providers"
	"github.com/openpubkey/openpubkey/util"
	"github.com/openpubkey/opkssh/commands/config"
	"github.com/openpubkey/opkssh/sshcert"
	"github.com/spf13/afero"
	"github.com/thediveo/enumflag/v2"
	"golang.org/x/crypto/ed25519"
	"golang.org/x/crypto/ssh"
	"golang.org/x/crypto/ssh/agent"
)

// KeyType is the algorithm to use for the user's key pair. This is used both by OpenPubkey as algorithm for upk (user public key) and by SSH for public key in the SSH certificate generated by opkssh.
type KeyType enumflag.Flag

const (
	ECDSA KeyType = iota
	ED25519
)

func (k KeyType) String() string {
	switch k {
	case ECDSA:
		return "ecdsa"
	case ED25519:
		return "ed25519"
	default:
		return "unknown"
	}
}

// DefaultSSHKeyFileNames are the file names ssh key pairs that opkssh may
// write to in ~/.ssh/ during login. These are used by both login and logout
// so that if a new key type is added, logout will automatically pick it up.
var DefaultSSHKeyFileNames = map[KeyType][]string{
	ECDSA:   {"id_ecdsa", "id_ecdsa_sk"},
	ED25519: {"id_ed25519", "id_ed25519_sk"},
}

// LoginCmd represents the login command that performs OIDC authentication and generates SSH certificates.
type LoginCmd struct {
	// Inputs
	Fs                    afero.Fs
	AutoRefreshArg        bool   // Automatically refresh PK token after login
	ConfigPathArg         string // Path to the client config file.
	CreateConfigArg       bool   // Creates a client config file if it does not exist
	ConfigureArg          bool   // Apply changes to ssh config and create ~/.ssh/opkssh directory
	LogDirArg             string // Directory to write output logs
	SendAccessTokenArg    bool   // Send the Access Token as well as the PK Token in the SSH cert. The Access Token is used to call the userinfo endpoint to get claims not included in the ID Token
	DisableBrowserOpenArg bool   // Disable opening the browser. Useful for choosing the browser you want to use
	PrintIdTokenArg       bool   // Print out the contents of the id_token. Useful for inspecting claims and troubleshooting
	KeyPathArg            string // Path where SSH private key is written
	ProviderArg           string // OpenID Provider specification in the format: <issuer>,<client_id> or <issuer>,<client_id>,<client_secret> or <issuer>,<client_id>,<client_secret>,<scopes>
	ProviderAliasArg      string
	KeyTypeArg            KeyType
	PrintKeyArg           bool // Print the raw private key and SSH cert to stdout instead of writing them to the filesystem
	InspectCertArg        bool // Display a human-readable inspection of the generated SSH certificate (public information only)
	SSHConfigured         bool
	Verbosity             int // Default verbosity is 0, 1 is verbose, 2 is debug
	RemoteRedirectURI     string
	PrincipalsArg         []string // The principals that will be included in the generated SSH cert. If not specified, it functions as a wildcard and will work for any principals.
	AgentLifetimeArg      string   // How long ssh-agent should retain the certificate (--lifetime flag; overrides agent_lifetime in the client config)
	AddKeyToAgent         bool     // Load the generated certificate into the ssh-agent at SSH_AUTH_SOCK. The zero value leaves this off so that a LoginCmd built directly, as tests build it, never reaches a real agent; main.go turns it on for the CLI.

	overrideProvider *providers.OpenIdProvider // Used in tests to override the provider to inject a mock provider
	// State
	Config *config.ClientConfig
	// agentCert is the certificate this command last loaded into the agent.
	// A refresh mints a replacement under the same private key but a different
	// certificate blob, which the agent stores as a separate identity, so the
	// previous one has to be removed explicitly.
	agentCert *ssh.Certificate

	// Outputs
	pkt    *pktoken.PKToken
	signer crypto.Signer
	alg    jose.KeyAlgorithm
	client *client.OpkClient

	// For testing
	OutWriter io.Writer // Captures non-logged output that would normally be written to stdout
}

// NewLogin creates a new LoginCmd instance with the provided arguments.
func NewLogin(autoRefreshArg bool, configPathArg string, createConfigArg bool, configureArg bool, logDirArg string,
	sendAccessTokenArg bool, disableBrowserOpenArg bool, printIdTokenArg bool,
	providerArg string, printKeyArg bool, keyPathArg string, providerAliasArg string, keyTypeArg KeyType,
	remoteRedirectUri string, inspectCertArg bool, principalsArg []string, agentLifetimeArg string,
) *LoginCmd {
	return &LoginCmd{
		Fs:                    afero.NewOsFs(),
		AutoRefreshArg:        autoRefreshArg,
		ConfigPathArg:         configPathArg,
		CreateConfigArg:       createConfigArg,
		ConfigureArg:          configureArg,
		LogDirArg:             logDirArg,
		SendAccessTokenArg:    sendAccessTokenArg,
		DisableBrowserOpenArg: disableBrowserOpenArg,
		PrintIdTokenArg:       printIdTokenArg,
		KeyPathArg:            keyPathArg,
		ProviderArg:           providerArg,
		PrintKeyArg:           printKeyArg,
		InspectCertArg:        inspectCertArg,
		ProviderAliasArg:      providerAliasArg,
		KeyTypeArg:            keyTypeArg,
		RemoteRedirectURI:     remoteRedirectUri,
		PrincipalsArg:         principalsArg,
		AgentLifetimeArg:      agentLifetimeArg,
	}
}

func (l *LoginCmd) Run(ctx context.Context) error {
	// If a log directory was provided, write any logs to a file in that directory AND stdout
	if l.LogDirArg != "" {
		logFilePath := filepath.Join(l.LogDirArg, "opkssh.log")
		logFile, err := l.Fs.OpenFile(logFilePath, os.O_APPEND|os.O_WRONLY|os.O_CREATE, 0o660)
		if err != nil {
			log.Printf("Failed to open log for writing: %v \n", err)
		}
		defer logFile.Close()
		multiWriter := io.MultiWriter(os.Stdout, logFile)
		log.SetOutput(multiWriter)
	} else {
		log.SetOutput(os.Stdout)
	}

	if l.Verbosity >= 2 {
		log.Printf("DEBUG: running login command with args: %+v", *l)
	}

	// If the Config has been set in the struct don't replace it. This is useful for testing
	if l.Config == nil {
		configFound, err := config.ResolveClientConfigPath(l.Fs, &l.ConfigPathArg)
		if err != nil {
			return err
		}
		if configFound {
			if l.CreateConfigArg {
				log.Printf("--create-config=true but config file already exists at %s", l.ConfigPathArg)
			}

			if client_config, err := config.GetClientConfigFromFile((l.ConfigPathArg), l.Fs); err != nil {
				return err
			} else {
				l.Config = client_config
				// Multiple config locations are possible (see
				// config.ResolveClientConfigPath); naming the winner
				// defuses silent shadowing, e.g. a hand-created legacy file
				// losing to an existing XDG-location config.
				if l.Verbosity >= 1 {
					log.Printf("using client config at %s", l.ConfigPathArg)
				}
			}
		} else {
			if l.CreateConfigArg {
				return config.CreateDefaultClientConfig(l.ConfigPathArg, l.Fs)
			} else {
				log.Printf("failed to find client config file to generate a default config, run `opkssh login --create-config` to create a default config file")
			}
			l.Config, err = config.NewClientConfig(config.DefaultClientConfig)
			if err != nil {
				return fmt.Errorf("failed to parse default config file: %w", err)
			}
			if l.Verbosity >= 1 {
				log.Printf("no client config file found; using built-in defaults (a new config would be created at %s)", l.ConfigPathArg)
			}
		}
	}

	if l.ConfigureArg {
		err := l.configureSSH()
		if err != nil {
			return fmt.Errorf("failed to configure SSH: %w", err)
		}
		return nil
	} else {
		l.checkSSHConfigured()
	}

	// Validate the requested ssh-agent lifetime up front, so that a typo in
	// --lifetime (or agent_lifetime in the client config) fails before the
	// browser-based OIDC flow starts rather than after authentication.
	if _, err := l.resolveAgentLifetimeSecs(); err != nil {
		return err
	}

	if kind, forgejoIssuer := detectActionsEnvironment(); kind == actionsEnvForgejo {
		l.Config.Providers = append(l.Config.Providers, config.ForgejoProviderConfig(forgejoIssuer))
	} else if kind == actionsEnvGithub {
		l.Config.Providers = append(l.Config.Providers, config.GitHubProviderConfig())
	}

	if os.Getenv(config.GITLAB_CI_ENVVAR) == "true" {
		l.Config.Providers = append(l.Config.Providers, config.GitlabCiProviderConfig(gitlabCiIssuer()))
	}

	var provider providers.OpenIdProvider
	if l.overrideProvider != nil {
		provider = *l.overrideProvider
	} else {
		op, chooser, err := l.determineProvider()
		if err != nil {
			return err
		}
		if chooser != nil {
			chooser.UseStdOutErr() // Set chooser to write to stdout and stderr
			provider, err = chooser.ChooseOp(ctx)
			if err != nil {
				return fmt.Errorf("error choosing provider: %w", err)
			}
		} else if op != nil {
			provider = op
			if configurableOp, ok := provider.(interface{ UseStdOutErr() }); ok {
				configurableOp.UseStdOutErr() // Set op to write to stdout and stderr (if supported)
			}
		} else {
			return fmt.Errorf("no provider found") // Either the provider or the chooser must be set. If this occurs we have a bug in the code.
		}
	}

	// This arg is true if set, so if it false it hasn't been set and
	// we should use the config value for the matching providing.
	// If it is true we ignore the config
	if !l.SendAccessTokenArg {
		if opConfig, ok := l.Config.GetByIssuer(provider.Issuer()); !ok {
			// This can happen if the provider is supplied via the command line or environment variables and thus not in the config
			log.Printf("Warning: could not find issuer %s in client config providers\n", provider.Issuer())
		} else {
			l.SendAccessTokenArg = opConfig.SendAccessToken
		}
	}

	// Execute login command
	if l.AutoRefreshArg {
		if providerRefreshable, ok := provider.(providers.RefreshableOpenIdProvider); ok {
			err := l.LoginWithRefresh(ctx, providerRefreshable, l.PrintIdTokenArg, l.KeyPathArg)
			if err != nil {
				return fmt.Errorf("error logging in: %w", err)
			}
		} else {
			return fmt.Errorf("supplied OpenID Provider (%v) does not support auto-refresh and auto-refresh argument set to true", provider.Issuer())
		}
	} else {
		err := l.Login(ctx, provider, l.PrintIdTokenArg, l.KeyPathArg)
		if err != nil {
			return fmt.Errorf("error logging in: %w", err)
		}
	}
	return nil
}

func (l *LoginCmd) configureSSH() error {

	userhomeDir, err := os.UserHomeDir()
	if err != nil {
		return fmt.Errorf("failed to get user config dir: %v", err)
	}

	const includeDirective = "Include ~/.ssh/opkssh/config"
	const opkSshDir = ".ssh/opkssh"
	var userSshConfig = filepath.Join(userhomeDir, ".ssh/config")
	var userOpkSshDir = filepath.Join(userhomeDir, opkSshDir)
	var userOpkSshConfig = filepath.Join(userOpkSshDir, "config")

	if _, err := l.Fs.Stat(userOpkSshConfig); err == nil {
		log.Println("--configure but already configured")
	}

	log.Printf("Creating config directory at %s", userOpkSshDir)

	afs := &afero.Afero{Fs: l.Fs}
	err = afs.MkdirAll(userOpkSshDir, 0o0700)
	if err != nil {
		return fmt.Errorf("failed to create opkssh SSH directory: %w", err)
	}

	log.Printf("Creating config file at %s", userOpkSshConfig)

	file, err := afs.OpenFile(userOpkSshConfig, os.O_CREATE, 0o0600)
	if err != nil {
		return fmt.Errorf("failed to create opkssh SSH directory: %w", err)
	}
	defer file.Close()

	log.Printf("Adding include directive to SSH config at %s", "~/.ssh/config")

	content, err := afs.ReadFile(userSshConfig)
	if err != nil && !errors.Is(err, os.ErrNotExist) {
		return fmt.Errorf("failed to read SSH config file: %w", err)
	}

	if strings.Contains(string(content), includeDirective) {
		log.Println("Found include directive file in SSH config, skipping...")
	} else {
		// construct new SSH config
		content = slices.Concat([]byte(includeDirective+"\n\n"), content)

		err = afs.WriteFile(userSshConfig, content, 0o0600)
		if err != nil {
			return fmt.Errorf("failed to write SSH config file: %w", err)
		}
	}

	l.SSHConfigured = true
	log.Println("Configured SSH identity directory")
	return nil
}

func (l *LoginCmd) checkSSHConfigured() {

	userhomeDir, err := os.UserHomeDir()
	if err != nil {
		log.Printf("Failed to get user config dir: %v", err)
		return
	}

	const includeDirective = "Include ~/.ssh/opkssh/config"
	const opkSshDir = ".ssh/opkssh"
	var userSshConfig = filepath.Join(userhomeDir, ".ssh/config")
	var userOpkSshDir = filepath.Join(userhomeDir, opkSshDir)
	var userOpkSshConfig = filepath.Join(userOpkSshDir, "config")

	afs := &afero.Afero{Fs: l.Fs}

	content, err := afs.ReadFile(userSshConfig)
	if err != nil {
		// no user SSH config, could not have included ours
		return
	}

	if !strings.Contains(string(content), includeDirective) {
		// no include directive
		return
	}

	_, err = afs.Stat(userOpkSshConfig)
	if err != nil {
		// opkssh ssh config missing
		return
	}

	fmt.Println("OPK SSH identity directory is configured")

	l.SSHConfigured = true
}

func (l *LoginCmd) determineProvider() (providers.OpenIdProvider, *choosers.WebChooser, error) {
	openBrowser := !l.DisableBrowserOpenArg

	var defaultProviderAlias string
	var providerConfigs []config.ProviderConfig
	var provider providers.OpenIdProvider
	var err error

	// If the user has supplied commandline arguments for the provider, short circuit and use providerArg
	if l.ProviderArg != "" {
		providerConfig, err := config.NewProviderConfigFromString(l.ProviderArg, false)
		if err != nil {
			return nil, nil, fmt.Errorf("error parsing provider argument: %w", err)
		}

		if l.RemoteRedirectURI != "" {
			// Override the remote redirect URI
			providerConfig.RemoteRedirectURI = l.RemoteRedirectURI
		}

		if provider, err = providerConfig.ToProvider(openBrowser); err != nil {
			return nil, nil, fmt.Errorf("error creating provider from config: %w", err)
		} else {
			return provider, nil, nil
		}
	}

	// Set the default provider from the env variable if specified
	defaultProviderEnv, _ := os.LookupEnv(config.OPKSSH_DEFAULT_ENVVAR)
	providerConfigsEnv, err := config.GetProvidersConfigFromEnv()
	if err != nil {
		return nil, nil, fmt.Errorf("error getting provider config from env: %w", err)
	}

	if l.ProviderAliasArg != "" {
		defaultProviderAlias = l.ProviderAliasArg
	} else if defaultProviderEnv != "" {
		defaultProviderAlias = defaultProviderEnv
	} else if l.Config.DefaultProvider != "" {
		defaultProviderAlias = l.Config.DefaultProvider
	} else {
		defaultProviderAlias = config.WEBCHOOSER_ALIAS
	}

	if providerConfigsEnv != nil {
		providerConfigs = providerConfigsEnv
	} else if len(l.Config.Providers) > 0 {
		providerConfigs = l.Config.Providers
	} else {
		return nil, nil, fmt.Errorf("no providers specified")
	}

	if strings.ToUpper(defaultProviderAlias) != config.WEBCHOOSER_ALIAS {
		providerMap, err := config.CreateProvidersMap(providerConfigs)
		if err != nil {
			return nil, nil, fmt.Errorf("error creating provider map: %w", err)
		}
		providerConfig, ok := providerMap[defaultProviderAlias]
		if !ok {
			// The CI/CD aliases are only registered when the corresponding
			// Actions environment is detected, so explain why they are missing
			kind, _ := detectActionsEnvironment()
			isForgejoEnv := kind == actionsEnvForgejo
			isGithubEnv := kind == actionsEnvGithub
			isCICDAlias := false
			switch strings.ToLower(defaultProviderAlias) {
			case "github":
				isCICDAlias = true
				if isForgejoEnv {
					return nil, nil, fmt.Errorf("this looks like a Forgejo Actions environment, use `opkssh login forgejo` instead")
				} else if !isGithubEnv {
					return nil, nil, fmt.Errorf("the %s provider only works inside a GitHub Actions workflow with the `id-token: write` permission (%s and %s are not set)", defaultProviderAlias, envActionsTokenRequestURL, envActionsTokenRequestToken)
				}
			case "forgejo", "codeberg":
				isCICDAlias = true
				if isGithubEnv {
					return nil, nil, fmt.Errorf("this looks like a GitHub Actions environment, use `opkssh login github` instead")
				} else if !isForgejoEnv {
					return nil, nil, fmt.Errorf("the %s provider only works inside a Forgejo Actions workflow with `enable-openid-connect: true` (%s and %s are not set)", defaultProviderAlias, envActionsTokenRequestURL, envActionsTokenRequestToken)
				}
			case "gitlab-ci":
				isCICDAlias = true
				if os.Getenv(config.GITLAB_CI_ENVVAR) != "true" {
					return nil, nil, fmt.Errorf("the %s provider only works inside a GitLab CI/CD pipeline (%s is not set to \"true\")", defaultProviderAlias, config.GITLAB_CI_ENVVAR)
				}
			}
			// Reaching here with a CI/CD alias means we are inside its
			// environment, so the provider was auto-registered and then
			// dropped when the env var replaced the whole provider list.
			if isCICDAlias && providerConfigsEnv != nil {
				return nil, nil, fmt.Errorf("the %s provider is registered automatically in this CI/CD environment, but %s is set and replaces the provider list; unset %s or add %s to it", defaultProviderAlias, config.OPKSSH_PROVIDERS_ENVVAR, config.OPKSSH_PROVIDERS_ENVVAR, defaultProviderAlias)
			}
			return nil, nil, fmt.Errorf("error getting provider config for alias %s", defaultProviderAlias)
		}
		if l.RemoteRedirectURI != "" {
			// Override the remote redirect URI
			providerConfig.RemoteRedirectURI = l.RemoteRedirectURI
		}

		provider, err = providerConfig.ToProvider(openBrowser)
		if err != nil {
			return nil, nil, fmt.Errorf("error creating provider from config: %w", err)
		}
		return provider, nil, nil
	} else {
		// If the default provider is WEBCHOOSER, we need to create a chooser and return it
		var providerList []providers.BrowserOpenIdProvider
		for _, providerConfig := range providerConfigs {
			// CI/CD providers (GitHub/Forgejo Actions) are not browser-based
			// and cannot be offered by the chooser
			if config.IsCICDProvider(providerConfig) {
				continue
			}
			if l.RemoteRedirectURI != "" {
				// Override the remote redirect URI
				providerConfig.RemoteRedirectURI = l.RemoteRedirectURI
			}
			op, err := providerConfig.ToProvider(openBrowser)
			if err != nil {
				return nil, nil, fmt.Errorf("error creating provider from config: %w", err)
			}
			browserOp, ok := op.(providers.BrowserOpenIdProvider)
			if !ok {
				return nil, nil, fmt.Errorf("provider for issuer %s does not support browser-based login", providerConfig.Issuer)
			}
			providerList = append(providerList, browserOp)
		}

		// The chooser would otherwise serve a page with no providers on it
		// and wait forever for a selection that cannot be made.
		if len(providerList) == 0 {
			return nil, nil, fmt.Errorf("no browser-based providers configured to choose from; CI/CD providers cannot be used with the web chooser, specify one by alias instead, e.g. `opkssh login forgejo`")
		}

		chooser := choosers.NewWebChooser(
			providerList, openBrowser,
		)
		return nil, chooser, nil
	}
}

func (l *LoginCmd) login(ctx context.Context, provider providers.OpenIdProvider, printIdToken bool, seckeyPath string) (*LoginCmd, error) {
	var err error

	var alg jose.KeyAlgorithm
	switch l.KeyTypeArg {
	case ECDSA:
		alg = jose.ES256
	case ED25519:
		alg = jose.EdDSA
	default:
		return nil, fmt.Errorf("unsupported key type (%s); use -t <%s|%s>", l.KeyTypeArg.String(), ECDSA.String(), ED25519.String())
	}

	signer, err := util.GenKeyPair(alg)
	if err != nil {
		return nil, fmt.Errorf("failed to generate keypair: %w", err)
	}

	opkClient, err := client.New(provider, client.WithSigner(signer, alg))
	if err != nil {
		return nil, err
	}

	pkt, err := opkClient.Auth(ctx)
	if err != nil {
		return nil, err
	}

	l.pkt = pkt

	var accessToken []byte
	if l.SendAccessTokenArg {
		accessToken = opkClient.GetAccessToken()
		if accessToken == nil {
			return nil, fmt.Errorf("access token required but provider (%s) did not set access-token", opkClient.Op.Issuer())
		}
	}

	if l.PrincipalsArg == nil {
		// If principals field is empty sshd automatically rejects the SSH certificate.
		// We use opkssh-wildcard as placeholder so that we can allow the OPK
		// verifier to make this policy decision instead of sshd.
		// See https://github.com/openpubkey/opkssh/pull/513
		l.PrincipalsArg = []string{"opkssh-wildcard"}
	}

	certBytes, seckeySshPem, err := createSSHCertWithAccessToken(pkt, accessToken, signer, l.PrincipalsArg)
	if err != nil {
		return nil, fmt.Errorf("failed to generate SSH cert: %w", err)
	}

	// Write ssh secret key and public key to filesystem. fallbackKeyPath is
	// set when the default key slots were all taken by other identities and
	// the keys landed in the opkssh identity directory instead.
	var fallbackKeyPath string
	if l.PrintKeyArg {
		w := l.out()
		fmt.Fprintln(w, string(certBytes))    // Base64 encoded SSH cert
		fmt.Fprintln(w, string(seckeySshPem)) // SSH private key in OpenSSH native format
	} else if fallbackKeyPath, err = l.writeKeysToDestination(seckeyPath, seckeySshPem, certBytes); err != nil {
		return nil, err
	}

	addedToAgent := l.maybeAddCertToAgent(certBytes, signer)
	// The remediation warning is decided after the agent attempt: keys written
	// to the fallback location are not tried by ssh on their own, so the user
	// must hear about it exactly when no agent ended up holding the key either.
	if !l.PrintKeyArg && fallbackKeyPath != "" && !addedToAgent {
		fmt.Fprintf(l.out(), "warning: ssh will not try %s automatically and no ssh-agent holds it; add an IdentityFile entry for it, use -i, or run `opkssh login --configure`\n", fallbackKeyPath)
	}

	if printIdToken {
		idTokenStr, err := PrettyIdToken(*pkt)
		if err != nil {
			return nil, fmt.Errorf("failed to format ID Token: %w", err)
		}

		fmt.Fprintf(l.out(), "id_token:\n%s\n", idTokenStr)
	}

	if l.InspectCertArg {
		inspect := NewInspectCmd(string(certBytes), l.out())
		if err := inspect.Run(); err != nil {
			return nil, fmt.Errorf("failed to inspect SSH cert: %w", err)
		}
	}

	idStr, err := IdentityString(*pkt)
	if err != nil {
		return nil, fmt.Errorf("failed to parse ID Token: %w", err)
	}
	fmt.Printf("Keys generated for identity\n%s\n", idStr)

	return &LoginCmd{
		pkt:           pkt,
		signer:        signer,
		client:        opkClient,
		alg:           alg,
		PrincipalsArg: l.PrincipalsArg,
	}, nil
}

// Login performs the OIDC login procedure and creates the SSH certs/keys in the
// default SSH key location.
func (l *LoginCmd) Login(ctx context.Context, provider providers.OpenIdProvider, printIdToken bool, seckeyPath string) error {
	_, err := l.login(ctx, provider, printIdToken, seckeyPath)
	return err
}

// LoginWithRefresh performs the OIDC login procedure, creates the SSH
// certs/keys in the default SSH key location, and continues to run and refresh
// the PKT (and create new SSH certs) indefinitely as its token expires. This
// function only returns if it encounters an error or if the supplied context is
// cancelled.
func (l *LoginCmd) LoginWithRefresh(ctx context.Context, provider providers.RefreshableOpenIdProvider, printIdToken bool, seckeyPath string) error {
	if loginResult, err := l.login(ctx, provider, printIdToken, seckeyPath); err != nil {
		return err
	} else {
		// Fail fast rather than dying on the first refresh.
		if !loginResult.client.HasRefreshToken() {
			return fmt.Errorf("provider (%s) did not issue a refresh token", provider.Issuer())
		}
		var claims struct {
			Expiration int64 `json:"exp"`
		}
		if err := json.Unmarshal(loginResult.pkt.Payload, &claims); err != nil {
			return err
		}

		for {
			// Sleep until a minute before expiration to give us time to refresh
			// the token and minimize any interruptions
			untilExpired := time.Until(time.Unix(claims.Expiration, 0)) - time.Minute
			// untilExpired := time.Until(time.Now().Add(15 * time.Second))
			log.Printf("Waiting for %v before attempting to refresh id_token...", untilExpired)
			select {
			case <-time.After(untilExpired):
				log.Print("Refreshing id_token...")
			case <-ctx.Done():
				return ctx.Err()
			}

			refreshedPkt, err := loginResult.client.Refresh(ctx)
			if err != nil {
				return err
			}
			loginResult.pkt = refreshedPkt

			var accessToken []byte
			if l.SendAccessTokenArg {
				accessToken = loginResult.client.GetAccessToken()
				if accessToken == nil {
					return fmt.Errorf("access token required but provider (%s) did not set access-token on refresh: %w", loginResult.client.Op.Issuer(), err)
				}
			}

			certBytes, seckeySshPem, err := createSSHCertWithAccessToken(loginResult.pkt, accessToken, loginResult.signer, loginResult.PrincipalsArg)
			if err != nil {
				return fmt.Errorf("failed to generate SSH cert: %w", err)
			}

			// Write ssh secret key and public key to filesystem
			if _, err := l.writeKeysToDestination(seckeyPath, seckeySshPem, certBytes); err != nil {
				return err
			}

			// Keep the agent holding the same certificate as the filesystem;
			// otherwise the agent keeps serving the certificate minted at the
			// initial login and stops participating once its lifetime elapses.
			l.maybeAddCertToAgent(certBytes, loginResult.signer)

			comPkt, err := refreshedPkt.Compact()
			if err != nil {
				return err
			}

			payloadB64 := payloadFromCompactPkt(comPkt)
			payload, err := base64.RawURLEncoding.DecodeString(string(payloadB64))
			if err != nil {
				return fmt.Errorf("refreshed ID token payload is not base64 encoded: %w", err)
			}

			if err = json.Unmarshal(payload, &claims); err != nil {
				return fmt.Errorf("malformed refreshed ID token payload: %w", err)
			}
		}
	}
}

func (l *LoginCmd) out() io.Writer {
	if l.OutWriter != nil {
		return l.OutWriter
	}
	return os.Stdout
}

// defaultAgentLifetime matches the opkssh server's default certificate
// expiration policy (24h from the ID token's iat claim, see docs/config.md),
// so the agent drops the key around the time servers stop accepting it.
const defaultAgentLifetime = 24 * time.Hour

// maybeAddCertToAgent applies the AddKeyToAgent gate, so that both paths that
// mint a certificate (the initial login and every refresh) make one decision
// about reaching the agent. It reports whether the key landed in an agent, so
// a caller can tell an unreachable key from one the agent is holding.
func (l *LoginCmd) maybeAddCertToAgent(certBytes []byte, signer crypto.Signer) bool {
	if l.AddKeyToAgent && !l.PrintKeyArg {
		return l.addCertToAgent(certBytes, signer)
	}
	return false
}

// addCertToAgent loads the certificate and its private key into the ssh-agent
// reachable via SSH_AUTH_SOCK, reporting whether the key landed in an agent.
// It always sets a lifetime. A certificate this command added earlier is
// removed first. The lifetime covers what the removal cannot: a later opkssh
// process has no record of this one's certificate, so without a lifetime every
// login would leave another certificate in the agent forever. Best-effort:
// every failure is a printed warning, never a login failure.
func (l *LoginCmd) addCertToAgent(certBytes []byte, signer crypto.Signer) bool {
	sock := os.Getenv("SSH_AUTH_SOCK")
	if sock == "" {
		return false
	}

	lifetimeSecs, err := l.resolveAgentLifetimeSecs()
	if err != nil {
		fmt.Fprintf(l.out(), "warning: not adding certificate to ssh-agent: %v\n", err)
		return false
	}

	pubkey, _, _, _, err := ssh.ParseAuthorizedKey(certBytes)
	if err != nil {
		fmt.Fprintf(l.out(), "warning: could not parse generated certificate for ssh-agent: %v\n", err)
		return false
	}
	cert, ok := pubkey.(*ssh.Certificate)
	if !ok {
		fmt.Fprintln(l.out(), "warning: generated key is not a certificate; not adding to ssh-agent")
		return false
	}

	conn, err := net.Dial("unix", sock)
	if err != nil {
		fmt.Fprintf(l.out(), "warning: could not connect to ssh-agent (%s): %v\n", sock, err)
		return false
	}
	defer conn.Close()

	// A dead socket (e.g. one left behind by agent forwarding) accepts the
	// dial but never responds; without a deadline the exchange would hang
	// the login after authentication has already succeeded.
	if err := conn.SetDeadline(time.Now().Add(5 * time.Second)); err != nil {
		fmt.Fprintf(l.out(), "warning: could not set ssh-agent I/O deadline: %v\n", err)
		return false
	}

	agentClient := agent.NewClient(conn)
	// Removing the superseded certificate is advisory: if the agent has
	// already dropped it, or never held it, the login proceeds regardless.
	if l.agentCert != nil {
		_ = agentClient.Remove(l.agentCert)
	}

	if err := agentClient.Add(agent.AddedKey{
		PrivateKey:   signer,
		Certificate:  cert,
		Comment:      "opkssh",
		LifetimeSecs: lifetimeSecs,
	}); err != nil {
		fmt.Fprintf(l.out(), "warning: failed to add certificate to ssh-agent: %v\n", err)
		return false
	}
	l.agentCert = cert
	fmt.Fprintf(l.out(), "Certificate added to ssh-agent (lifetime %s)\n", time.Duration(lifetimeSecs)*time.Second)
	return true
}

// resolveAgentLifetimeSecs picks how long ssh-agent retains the key: the
// --lifetime flag, else agent_lifetime from the client config, else
// defaultAgentLifetime. The result only bounds agent retention; it says
// nothing about how long the certificate is valid, because the client cannot
// know a server's expiration policy (servers compute it from the ID token's
// iat claim).
func (l *LoginCmd) resolveAgentLifetimeSecs() (uint32, error) {
	var source, value string
	switch {
	case l.AgentLifetimeArg != "":
		source, value = "--lifetime", l.AgentLifetimeArg
	case l.Config != nil && l.Config.AgentLifetime != "":
		source, value = "agent_lifetime in client config", l.Config.AgentLifetime
	default:
		return uint32(defaultAgentLifetime / time.Second), nil
	}

	d, err := parseDurationOrSeconds(value)
	if err != nil {
		return 0, fmt.Errorf("invalid %s value %q: %w", source, value, err)
	}
	// A sub-second duration truncates to LifetimeSecs 0, which the agent
	// protocol treats as no lifetime at all: the key would live forever, the
	// exact state the lifetime exists to prevent.
	if d < time.Second {
		return 0, fmt.Errorf("invalid %s value %q: must be at least 1 second", source, value)
	}
	if d > math.MaxUint32*time.Second {
		return 0, fmt.Errorf("invalid %s value %q: too large", source, value)
	}
	return uint32(d / time.Second), nil
}

// parseDurationOrSeconds parses a lifetime given either as a Go duration
// string (e.g. "8h", "45m") or as a raw number of seconds (e.g. "28800").
func parseDurationOrSeconds(s string) (time.Duration, error) {
	s = strings.TrimSpace(s)
	if s == "" {
		return 0, errors.New("empty duration")
	}
	if d, err := time.ParseDuration(s); err == nil {
		return d, nil
	}
	if sec, err := strconv.ParseInt(s, 10, 64); err == nil {
		// Check the bound before multiplying: time.Duration(sec)*time.Second
		// overflows int64 for large values and can wrap into a small
		// positive duration.
		if sec < 0 || sec > math.MaxUint32 {
			return 0, fmt.Errorf("seconds value %d out of range", sec)
		}
		return time.Duration(sec) * time.Second, nil
	}
	return 0, errors.New("expected a duration like 8h or 45m, or a number of seconds like 28800")
}

func createSSHCert(pkt *pktoken.PKToken, signer crypto.Signer, principals []string) ([]byte, []byte, error) {
	return createSSHCertWithAccessToken(pkt, nil, signer, principals)
}

func createSSHCertWithAccessToken(pkt *pktoken.PKToken, accessToken []byte, signer crypto.Signer, principals []string) ([]byte, []byte, error) {
	cert, err := sshcert.New(pkt, accessToken, principals)
	if err != nil {
		return nil, nil, err
	}
	sshSigner, err := ssh.NewSignerFromSigner(signer)
	if err != nil {
		return nil, nil, err
	}

	var keyAlgos []string
	switch signer.(type) {
	case *ecdsa.PrivateKey:
		keyAlgos = []string{ssh.KeyAlgoECDSA256}
	case ed25519.PrivateKey:
		keyAlgos = []string{ssh.KeyAlgoED25519}
	default:
		return nil, nil, fmt.Errorf("unsupported key type: %T", signer)
	}

	signerMas, err := ssh.NewSignerWithAlgorithms(sshSigner.(ssh.AlgorithmSigner), keyAlgos)
	if err != nil {
		return nil, nil, err
	}

	sshCert, err := cert.SignCert(signerMas)
	if err != nil {
		return nil, nil, err
	}
	certBytes := ssh.MarshalAuthorizedKey(sshCert)
	// Remove newline character that MarshalAuthorizedKey() adds
	certBytes = certBytes[:len(certBytes)-1]

	seckeySsh, err := ssh.MarshalPrivateKey(signer, "openpubkey cert")
	if err != nil {
		return nil, nil, err
	}
	seckeySshBytes := pem.EncodeToMemory(seckeySsh)

	return certBytes, seckeySshBytes, nil
}

// writeKeysToDestination writes the SSH private key and certificate to the
// correct location on the filesystem, enforcing the following precedence:
//
//  1. seckeyPath (the --private-key-file/-i argument) if set
//  2. the opkssh identity directory (~/.ssh/opkssh) if it has been configured
//  3. the default ~/.ssh location
//
// The --private-key-file argument always has the highest precedence so that an
// explicitly requested path is never overridden by the opkssh identity
// directory or the default location. See https://github.com/openpubkey/opkssh/issues/524
func (l *LoginCmd) writeKeysToDestination(seckeyPath string, seckeySshPem []byte, certBytes []byte) (string, error) {
	switch {
	case seckeyPath != "":
		// If we have set seckeyPath then write it there
		if err := l.writeKeys(seckeyPath, seckeyPath+"-cert.pub", seckeySshPem, certBytes); err != nil {
			return "", fmt.Errorf("failed to write SSH keys to filesystem: %w", err)
		}
		return "", nil
	case l.SSHConfigured:
		if _, err := l.writeKeysToOpkSSHDir(seckeySshPem, certBytes, pktIdentity(l.pkt)); err != nil {
			return "", fmt.Errorf("failed to write SSH keys to OPK SSH dir: %w", err)
		}
		return "", nil
	default:
		// If keyPath isn't set then write it to the default location
		fallbackKeyPath, err := l.writeKeysToSSHDir(seckeySshPem, certBytes, pktIdentity(l.pkt))
		if err != nil {
			return "", fmt.Errorf("failed to write SSH keys to filesystem: %w", err)
		}
		return fallbackKeyPath, nil
	}
}

func (l *LoginCmd) writeKeysToOpkSSHDir(secKeyPem []byte, certBytes []byte, identity keyIdentity) (string, error) {

	const (
		opkSshPath     = ".ssh/opkssh"
		configFileName = "config"
	)

	userhomeDir, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}

	opkSshUserPath := filepath.Join(userhomeDir, opkSshPath)
	opkSshConfigPath := filepath.Join(opkSshUserPath, configFileName)

	// The directory and its config fragment are created on demand: this
	// writer also serves logins whose default key slots are all taken, which
	// may happen before --configure has ever run. Writing the IdentityFile
	// line is inert until ~/.ssh/config gains the Include directive, but it
	// makes a later --configure pick every key up instantly.
	if err := l.Fs.MkdirAll(opkSshUserPath, 0o700); err != nil {
		return "", err
	}

	afs := &afero.Afero{Fs: l.Fs}

	sshKeyName := l.makeSSHKeyFileName(l.pkt)
	privKeyPath := filepath.Join(opkSshUserPath, sshKeyName)
	pubKeyPath := privKeyPath + "-cert.pub"

	// A different account at the same provider maps to the same
	// <issuer>-<client_id> file name; it must not be clobbered. Policy for
	// this tier: a slot is writable only when it is fully free or the
	// existing certificate provably belongs to the same identity; anything
	// else (different identity, unparseable, or a private key without its
	// certificate) disambiguates with an identity tag — and the same rule
	// applies at the tagged path, erroring rather than silently replacing a
	// foreign occupant.
	if !dirSlotWritable(classifySlot(l.Fs, privKeyPath, pubKeyPath, identity)) {
		// Tagging a nothing would produce a stable but non-identifying file
		// name; failing loudly is clearer (unreachable in practice — the PK
		// token just completed a login).
		if !identity.valid {
			return "", errors.New("cannot disambiguate the key file name: no identity could be extracted from the PK token")
		}
		sshKeyName = sshKeyName + "-" + identityTag(identity)
		privKeyPath = filepath.Join(opkSshUserPath, sshKeyName)
		pubKeyPath = privKeyPath + "-cert.pub"
		if !dirSlotWritable(classifySlot(l.Fs, privKeyPath, pubKeyPath, identity)) {
			return "", fmt.Errorf("key file %s exists and holds a different identity; remove it or use -i to pick another path", privKeyPath)
		}
	}

	comment := " openpubkey: " + commentField(identity.issuer) + " " + commentField(identity.audience)

	// Write the key files before the config fragment references them, so a
	// key-write failure cannot leave a dangling IdentityFile entry.
	if err := l.writeKeysComment(privKeyPath, pubKeyPath, secKeyPem, certBytes, comment); err != nil {
		return "", err
	}

	// add key to config. Whole-line match (a tagged path contains its
	// untagged prefix, so a substring check would wrongly skip needed
	// entries); when the line is already present the fragment is left
	// entirely untouched.
	configContent, err := afs.ReadFile(opkSshConfigPath)
	if err != nil {
		if !os.IsNotExist(err) {
			return "", fmt.Errorf("failed to read opk ssh config file (%s): %w", opkSshConfigPath, err)
		}
		configContent = nil
	}
	identityLine := identityFileLine(privKeyPath)
	hasLine := slices.ContainsFunc(fragmentLines(configContent), func(line string) bool {
		return strings.TrimSpace(line) == identityLine
	})
	if !hasLine {
		configContent = slices.Concat([]byte(identityLine+"\n"), configContent)
		if err := afs.WriteFile(opkSshConfigPath, configContent, 0600); err != nil {
			return "", fmt.Errorf("failed to write opk ssh config file (%s): %w", opkSshConfigPath, err)
		}
	}
	return privKeyPath, nil
}

// dirSlotWritable is the opkssh identity directory's write policy over
// classified slots: only a fully free slot or a provably same-identity
// certificate may be written; every other state disambiguates or errors.
func dirSlotWritable(info slotInfo) bool {
	if info.cert == certSameIdentity {
		return true
	}
	return info.cert == certAbsent && !info.privExists
}

func (l *LoginCmd) writeKeysToSSHDir(seckeySshPem []byte, certBytes []byte, identity keyIdentity) (string, error) {
	homePath, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	sshPath := filepath.Join(homePath, ".ssh")

	// Make ~/.ssh if folder does not exist
	if err := l.Fs.MkdirAll(sshPath, os.ModePerm); err != nil {
		return "", err
	}

	// For ssh to automatically find the key created by openpubkey when
	// connecting, we prefer one of the default ssh key paths.
	keyFileNames, ok := DefaultSSHKeyFileNames[l.KeyTypeArg]
	if !ok {
		return "", fmt.Errorf("key type (%s) has no default output file name; use -i <filePath>", l.KeyTypeArg.String())
	}

	for _, keyFilename := range keyFileNames {
		seckeyPath := filepath.Join(sshPath, keyFilename)
		pubkeyPath := seckeyPath + "-cert.pub"
		info := classifySlot(l.Fs, seckeyPath, pubkeyPath, identity)

		// Policy for the default tier, preserving pre-change behavior
		// exactly: an absent private key makes the slot writable even over
		// an orphaned or foreign certificate. With the private key present,
		// only a provably same-identity certificate may be overwritten —
		// plus the legacy case of a certificate with no extractable PK
		// token identity but the comment exactly "openpubkey", which was
		// the pre-change reuse condition; this repo does not control the PK
		// token wire format's history, and demoting a re-login to a
		// relocated key on a parse failure would silently shadow the fresh
		// key with the stale file. A parseable certificate for a different
		// identity, an orphaned private key, and an unreadable certificate
		// are protected.
		if !info.privExists || info.cert == certSameIdentity || info.cert == certLegacyComment {
			return "", l.writeKeys(seckeyPath, pubkeyPath, seckeySshPem, certBytes)
		}
		if info.cert == certUnreadable {
			log.Println("Failed to read or parse:", pubkeyPath)
		}
	}

	// Every default slot belongs to someone else: write a per-identity file
	// into the opkssh identity directory instead of clobbering. ssh does not
	// try non-default file names on its own — the key is reachable through
	// ssh-agent (login loads it there when one is available), an
	// IdentityFile entry, -i, or the --configure mechanism.
	return l.writeKeysToOpkSSHDir(seckeySshPem, certBytes, identity)
}

// keyIdentity is the identity triple a written key file is bound to. The
// zero value is invalid; equality is only ever established through sameAs.
type keyIdentity struct {
	issuer   string
	audience string
	subject  string
	valid    bool
}

// sameAs reports whether two identities are provably the same. It fails
// closed by construction: an invalid identity — nil token, failed claim
// extraction, unparseable certificate — never compares equal to anything,
// because equality is what authorizes overwriting a key file.
func (k keyIdentity) sameAs(other keyIdentity) bool {
	return k.valid && other.valid && k == other
}

// pktIdentity extracts the identity triple from a PK token, failing closed
// (see sameAs) when the token is nil or any component cannot be extracted.
func pktIdentity(pkt *pktoken.PKToken) keyIdentity {
	if pkt == nil {
		return keyIdentity{}
	}
	issuer, errIss := pkt.Issuer()
	audience, errAud := pkt.Audience()
	subject, errSub := pkt.Subject()
	if errIss != nil || errAud != nil || errSub != nil {
		return keyIdentity{}
	}
	return keyIdentity{issuer: issuer, audience: audience, subject: subject, valid: true}
}

// certFileIdentity extracts the identity from the bytes of a certificate
// file written by opkssh; invalid when the file does not hold an opkssh
// certificate with an extractable identity.
func certFileIdentity(certBytes []byte) keyIdentity {
	pubkey, _, _, _, err := ssh.ParseAuthorizedKey(certBytes)
	if err != nil {
		return keyIdentity{}
	}
	return certKeyIdentity(pubkey)
}

// certKeyIdentity extracts the identity from an already-parsed public key.
func certKeyIdentity(pubkey ssh.PublicKey) keyIdentity {
	cert, isCert := pubkey.(*ssh.Certificate)
	if !isCert {
		return keyIdentity{}
	}
	smuggler := &sshcert.SshCertSmuggler{SshCert: cert}
	pkt, err := smuggler.GetPKToken()
	if err != nil {
		return keyIdentity{}
	}
	return pktIdentity(pkt)
}

// certState classifies the -cert.pub side of a key-file slot relative to the
// identity now logging in.
type certState int

const (
	certAbsent        certState = iota
	certSameIdentity            // provably this identity's certificate
	certLegacyComment           // no extractable identity, comment exactly "openpubkey"
	certForeign                 // anything else parseable (another identity, or not opkssh's)
	certUnreadable              // exists but could not be read or parsed
)

// slotInfo is a classified key-file slot: whether the private key file is
// present, and what the certificate side holds.
type slotInfo struct {
	privExists bool
	cert       certState
}

// classifySlot answers "who holds this slot?" for a private-key path and its
// -cert.pub companion. It is the mechanism shared by every key-writing tier;
// each tier maps the states to its own write policy.
func classifySlot(fs afero.Fs, privKeyPath, pubKeyPath string, identity keyIdentity) slotInfo {
	info := slotInfo{privExists: fsFileExists(fs, privKeyPath)}
	if !fsFileExists(fs, pubKeyPath) {
		return info
	}
	certBytes, err := (&afero.Afero{Fs: fs}).ReadFile(pubKeyPath)
	if err != nil {
		info.cert = certUnreadable
		return info
	}
	pubkey, comment, _, _, err := ssh.ParseAuthorizedKey(certBytes)
	if err != nil {
		info.cert = certUnreadable
		return info
	}
	existing := certKeyIdentity(pubkey)
	switch {
	case existing.sameAs(identity):
		info.cert = certSameIdentity
	case !existing.valid && comment == "openpubkey":
		info.cert = certLegacyComment
	default:
		info.cert = certForeign
	}
	return info
}

// identityFileLine renders a config-fragment entry for a private key path.
// The format is a contract between login (which writes entries) and logout
// (which removes them); both sides must go through this function.
func identityFileLine(privKeyPath string) string {
	return "IdentityFile " + privKeyPath
}

// fragmentLines splits config-fragment content into lines, tolerating both
// \n and \r\n endings.
func fragmentLines(fragment []byte) []string {
	return strings.Split(strings.ReplaceAll(string(fragment), "\r\n", "\n"), "\n")
}

// commentField preserves the historical key-comment format, which printed
// "unknown" for a claim that could not be extracted rather than an empty
// field.
func commentField(s string) string {
	if s == "" {
		return "unknown"
	}
	return s
}

// identityTag returns a short, stable tag for an identity, used to
// disambiguate key file names for different accounts at the same provider.
// The full triple is hashed — not the subject alone — so that two client IDs
// sharing a truncated prefix in the file name cannot alias, and because some
// OPs use email addresses as subjects, which do not belong in file names.
func identityTag(identity keyIdentity) string {
	digest := sha256.Sum256([]byte(identity.issuer + "|" + identity.audience + "|" + identity.subject))
	return hex.EncodeToString(digest[:4])
}

func (l *LoginCmd) writeKeys(seckeyPath string, pubkeyPath string, seckeySshPem []byte, certBytes []byte) error {
	// Write ssh secret key to filesystem
	afs := &afero.Afero{Fs: l.Fs}
	if err := afs.WriteFile(seckeyPath, seckeySshPem, 0o600); err != nil {
		return err
	}

	fmt.Printf("Writing opk ssh public key to %s and corresponding secret key to %s\n", pubkeyPath, seckeyPath)

	certBytes = append(certBytes, []byte(" openpubkey")...)
	// Write ssh public key (certificate) to filesystem
	return afs.WriteFile(pubkeyPath, certBytes, 0o644)
}

func (l *LoginCmd) writeKeysComment(seckeyPath string, pubkeyPath string, seckeySshPem []byte, certBytes []byte, pubKeyComment string) error {
	// Write ssh secret key to filesystem
	afs := &afero.Afero{Fs: l.Fs}
	if err := afs.WriteFile(seckeyPath, seckeySshPem, 0o600); err != nil {
		return err
	}

	fmt.Printf("Writing opk ssh public key to %s and corresponding secret key to %s\n", pubkeyPath, seckeyPath)

	certBytes = append(certBytes, ' ')
	certBytes = append(certBytes, pubKeyComment...)
	// Write ssh public key (certificate) to filesystem
	return afs.WriteFile(pubkeyPath, certBytes, 0o644)
}

func (l *LoginCmd) makeSSHKeyFileName(pkt *pktoken.PKToken) string {

	regex := regexp.MustCompile(`[^a-zA-Z0-9_\-.]+`)

	issuer, err := pkt.Issuer()
	if err != nil {
		issuer = "unknown"
	}

	issuer, _ = strings.CutPrefix(issuer, "https://")

	audience, err := pkt.Audience()
	if err != nil {
		audience = "unknown"
	}

	// shorten clientID if it is too long
	if len(audience) > 20 {
		audience = audience[:20]
	}

	keyName := issuer + "-" + audience
	keyName = regex.ReplaceAllString(keyName, "_")

	return keyName
}

func fsFileExists(fs afero.Fs, fPath string) bool {
	// Stat, not Open: the previous Open-based check leaked a file descriptor
	// per call.
	_, err := fs.Stat(fPath)
	return !errors.Is(err, os.ErrNotExist)
}

// IdentityString returns a string representation of the identity from the PK Token.
// e.g "Email, sub, issuer, audience"
func IdentityString(pkt pktoken.PKToken) (string, error) {
	idt, err := oidc.NewJwt(pkt.OpToken)
	if err != nil {
		return "", err
	}
	claims := idt.GetClaims()
	if claims.Email == "" {
		return fmt.Sprintf(`WARNING: Email claim is missing from ID token. Policies based on email will not work.
Check if your client config has the correct scopes configured for this OpenID Provider (run with -v to see which config file is in use).
Sub, issuer, audience:
%s %s %s`, claims.Subject, claims.Issuer, claims.Audience), nil
	} else {
		return fmt.Sprintf("Email, sub, issuer, audience: \n%s %s %s %s", claims.Email, claims.Subject, claims.Issuer, claims.Audience), nil
	}
}

// PrettyIdToken returns a pretty-printed JSON representation of the ID Token claims.
func PrettyIdToken(pkt pktoken.PKToken) (string, error) {
	idt, err := oidc.NewJwt(pkt.OpToken)
	if err != nil {
		return "", err
	}
	idtJson, err := json.MarshalIndent(idt.GetClaims(), "", "  ")
	if err != nil {
		return "", err
	}
	return string(idtJson[:]), nil
}

// GitHub Actions and Forgejo Actions runners both inject
// envActionsTokenRequestURL/Token to let a workflow request an OIDC ID
// Token. config.GITLAB_CI_ENVVAR and config.CI_SERVER_URL_ENVVAR are GitLab
// CI/CD's equivalent markers, and githubActionsTokenRequestHostSuffix is the
// host of GitHub's ACTIONS_ID_TOKEN_REQUEST_URL, e.g.
// pipelines.actions.githubusercontent.com.
const (
	envActionsTokenRequestURL           = "ACTIONS_ID_TOKEN_REQUEST_URL"
	envActionsTokenRequestToken         = "ACTIONS_ID_TOKEN_REQUEST_TOKEN"
	githubActionsTokenRequestHostSuffix = "actions.githubusercontent.com"
)

// isActionsEnvironment detects a CI/CD workload identity environment
// (GitHub Actions or Forgejo Actions); both inject the same variables.
func isActionsEnvironment() bool {
	return os.Getenv(envActionsTokenRequestURL) != "" &&
		os.Getenv(envActionsTokenRequestToken) != ""
}

type actionsEnvKind int

const (
	actionsEnvNone actionsEnvKind = iota
	actionsEnvGithub
	actionsEnvForgejo
)

// detectActionsEnvironment identifies which Actions-compatible CI/CD
// environment is active. GitHub and Forgejo Actions inject the same env
// vars, so each is identified positively rather than by ruling out the
// other, which would misreport a third runner as GitHub.
func detectActionsEnvironment() (kind actionsEnvKind, forgejoIssuer string) {
	if !isActionsEnvironment() {
		return actionsEnvNone, ""
	}
	tokenRequestURL := os.Getenv(envActionsTokenRequestURL)
	if issuer, err := providers.ForgejoIssuerFromTokenRequestURL(tokenRequestURL); err == nil {
		return actionsEnvForgejo, issuer
	}
	if parsedURL, err := url.Parse(tokenRequestURL); err == nil && strings.HasSuffix(parsedURL.Host, githubActionsTokenRequestHostSuffix) {
		return actionsEnvGithub, ""
	}
	return actionsEnvNone, ""
}

// gitlabCiIssuer returns the GitLab instance URL for the current CI/CD
// pipeline, from the CI_SERVER_URL predefined variable, e.g.
// "https://gitlab.com" or a self-hosted instance's URL.
func gitlabCiIssuer() string {
	if issuer := os.Getenv(config.CI_SERVER_URL_ENVVAR); issuer != "" {
		return issuer
	}
	return "https://gitlab.com"
}

// payloadFromCompactPkt extracts the payload from a compact PK Token which
// is always the third part of the '.' separated string.
func payloadFromCompactPkt(compactPkt []byte) []byte {
	parts := bytes.Split(compactPkt, []byte("."))
	return parts[2]
}
