name: CI

# Runs CI for pull requests and pushes to main
on:
  pull_request:
  push:
    branches:
      - main
  # schedule:
  #   - cron: 0 14 * * MON-FRI # Every weekday at 14:00 UTC

jobs:
  # Check that binary can be built
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 5
    strategy:
      matrix:
        go-version: [1.23.x]
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}
    - name: Install dependencies
      run: go mod download
    - name: Build
      run: go build -v -o /dev/null
  # Run integration tests
  test:
    needs: build
    name: 'Integration Tests'
    runs-on: ${{ matrix.runs_on }}
    timeout-minutes: 8
    strategy:
      matrix:
        runs_on: [ubuntu-latest, ubuntu-24.04-arm]
        os: [ubuntu, centos, arch]
        exclude:
          - runs_on: ubuntu-24.04-arm
             os: arch
    env:
      OS_TYPE: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Install Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'go.mod'
    - name: Install Docker
      uses: docker/setup-buildx-action@v2
    - name: Install dependencies
      run: go mod download
    - name: Run integration tests
      run: go test -tags=integration ./test/integration -timeout=15m -count=1 -parallel=2 -v
